/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sisteminformasipuskesmas;

/**
 *
 * @author Asus
 */

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class RegisterFormAdmin extends javax.swing.JFrame {

    /**
     * Creates new form RegisterForm
     */
    public RegisterFormAdmin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jPanel1 = new javax.swing.JPanel();
        btnRegister = new javax.swing.JButton();
        pwdPassword = new javax.swing.JPasswordField();
        pwdPasswordConfirm = new javax.swing.JPasswordField();
        txtNamaAdmin = new javax.swing.JTextField();
        txtIDAdmin = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblClose = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblChange = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panel1.setBackground(new java.awt.Color(228, 241, 254));
        panel1.setPreferredSize(new java.awt.Dimension(720, 512));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(27, 117, 188), 3, true));

        btnRegister.setBackground(new java.awt.Color(27, 117, 188));
        btnRegister.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("REGISTER");
        btnRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegisterMouseExited(evt);
            }
        });
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        pwdPassword.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        pwdPassword.setForeground(new java.awt.Color(153, 153, 153));
        pwdPassword.setText("password");
        pwdPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pwdPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pwdPasswordFocusLost(evt);
            }
        });

        pwdPasswordConfirm.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        pwdPasswordConfirm.setForeground(new java.awt.Color(153, 153, 153));
        pwdPasswordConfirm.setText("password");
        pwdPasswordConfirm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pwdPasswordConfirmFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pwdPasswordConfirmFocusLost(evt);
            }
        });

        txtNamaAdmin.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtNamaAdmin.setForeground(new java.awt.Color(153, 153, 153));
        txtNamaAdmin.setText("nama admin");
        txtNamaAdmin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNamaAdminFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNamaAdminFocusLost(evt);
            }
        });

        txtIDAdmin.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtIDAdmin.setForeground(new java.awt.Color(153, 153, 153));
        txtIDAdmin.setText("id admin");
        txtIDAdmin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIDAdminFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIDAdminFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtIDAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamaAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwdPasswordConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwdPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(txtIDAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNamaAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pwdPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pwdPasswordConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(27, 117, 188));
        jLabel1.setText("SISTEM INFORMASI PUSKESMAS");

        jPanel2.setBackground(new java.awt.Color(27, 117, 188));

        lblClose.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/close24.png"))); // NOI18N
        lblClose.setText("x");
        lblClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });

        lblMinimize.setFont(new java.awt.Font("Tahoma", 1, 34)); // NOI18N
        lblMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/minimize24.png"))); // NOI18N
        lblMinimize.setText("-");
        lblMinimize.setToolTipText("");
        lblMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblClose, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblClose, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(lblMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblLogin.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblLogin.setText("already have an account");
        lblLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLoginMouseExited(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo-SIP.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("ADMIN");

        lblChange.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/change.png"))); // NOI18N
        lblChange.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblChangeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addComponent(jLabel2))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panel1Layout.createSequentialGroup()
                                        .addGap(95, 95, 95)
                                        .addComponent(lblLogin))))))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(lblChange)))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblChange))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLogin)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lblCloseMouseClicked

    private void lblMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMouseClicked

    private void lblLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMouseClicked
        // TODO add your handling code here:
        LoginFormAdmin lgfa = new LoginFormAdmin();
        lgfa.setVisible(true);
        lgfa.pack();
        lgfa.setLocationRelativeTo(null);
        lgfa.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_lblLoginMouseClicked

    private void txtIDAdminFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIDAdminFocusGained
        // TODO add your handling code here:
        if(txtIDAdmin.getText().trim().toLowerCase().equals("id admin"))
        {
            txtIDAdmin.setText("");
            txtIDAdmin.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtIDAdminFocusGained

    private void txtIDAdminFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIDAdminFocusLost
        // TODO add your handling code here:
        if(txtIDAdmin.getText().trim().equals("") || 
           txtIDAdmin.getText().trim().toLowerCase().equals("id admin"))
        {
            txtIDAdmin.setText("id admin");
            txtIDAdmin.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtIDAdminFocusLost

    private void txtNamaAdminFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNamaAdminFocusGained
        // TODO add your handling code here:
        if(txtNamaAdmin.getText().trim().toLowerCase().equals("nama admin"))
        {
            txtNamaAdmin.setText("");
            txtNamaAdmin.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtNamaAdminFocusGained

    private void txtNamaAdminFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNamaAdminFocusLost
        // TODO add your handling code here:
        if(txtNamaAdmin.getText().trim().equals("") || 
           txtNamaAdmin.getText().trim().toLowerCase().equals("nama admin"))
        {
            txtNamaAdmin.setText("nama admin");
            txtNamaAdmin.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtNamaAdminFocusLost

    private void pwdPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwdPasswordFocusGained
        // TODO add your handling code here:
        String pwd = String.valueOf(pwdPassword.getPassword());
        
        if(pwd.trim().toLowerCase().equals("password"))
        {
            pwdPassword.setText("");
            pwdPassword.setForeground(Color.black);
        }
    }//GEN-LAST:event_pwdPasswordFocusGained

    private void pwdPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwdPasswordFocusLost
        // TODO add your handling code here:
        String pwd = String.valueOf(pwdPassword.getPassword());
        
        if(pwd.trim().equals("") || 
           pwd.trim().toLowerCase().equals("password"))
        {
            pwdPassword.setText("password");
            pwdPassword.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_pwdPasswordFocusLost

    private void pwdPasswordConfirmFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwdPasswordConfirmFocusGained
        // TODO add your handling code here:
        String pwdc = String.valueOf(pwdPasswordConfirm.getPassword());
        
        if(pwdc.trim().toLowerCase().equals("password"))
        {
            pwdPasswordConfirm.setText("");
            pwdPasswordConfirm.setForeground(Color.black);
        }
    }//GEN-LAST:event_pwdPasswordConfirmFocusGained

    private void pwdPasswordConfirmFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwdPasswordConfirmFocusLost
        // TODO add your handling code here:
        String pwdc = String.valueOf(pwdPasswordConfirm.getPassword());
        
        if(pwdc.trim().equals("") || 
           pwdc.trim().toLowerCase().equals("password"))
        {
            pwdPasswordConfirm.setText("password");
            pwdPasswordConfirm.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_pwdPasswordConfirmFocusLost

    private void lblLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMouseEntered
        // TODO add your handling code here:
        lblLogin.setForeground(new Color(37,116,169));
    }//GEN-LAST:event_lblLoginMouseEntered

    private void lblLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMouseExited
        // TODO add your handling code here:
        lblLogin.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_lblLoginMouseExited

    private void btnRegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterMouseEntered
        // TODO add your handling code here:
        btnRegister.setBackground(new Color(27,117,188));
    }//GEN-LAST:event_btnRegisterMouseEntered

    private void btnRegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterMouseExited
        // TODO add your handling code here:
        btnRegister.setBackground(new Color(37,116,169));
    }//GEN-LAST:event_btnRegisterMouseExited

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        String idadmin = txtIDAdmin.getText();
        String namaadmin = txtNamaAdmin.getText();
        String pass = String.valueOf(pwdPassword.getPassword());
        String passconf = String.valueOf(pwdPasswordConfirm.getPassword());
        
        if(verifyFields())
        {
            PreparedStatement ps;
            ResultSet rs;
            String registerUserQuery = "INSERT INTO `admin`(`id_admin`, `nama_admin`, `password`) VALUES (?,?,?)";
            
            try {
                ps = connection.getConnection().prepareStatement(registerUserQuery);
                
                ps.setString(1, idadmin);
                ps.setString(2, namaadmin);
                ps.setString(3, pass);
                
                if(ps.executeUpdate() != 0){
                    JOptionPane.showMessageDialog(null, "Akun Berhasil Dibuat", "Register Berhasil", 2);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Cek Data", "Register Error", 2);
                }
            } catch (SQLException ex) {
                Logger.getLogger(RegisterFormAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void lblChangeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblChangeMouseClicked
        // TODO add your handling code here:
        RegisterFormPetugas rgfp = new RegisterFormPetugas();
        rgfp.setVisible(true);
        rgfp.pack();
        rgfp.setLocationRelativeTo(null);
        rgfp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_lblChangeMouseClicked

    public boolean verifyFields()
    {
        String idadmin = txtIDAdmin.getText();
        String namaadmin = txtNamaAdmin.getText();
        String pass = String.valueOf(pwdPassword.getPassword());
        String passconf = String.valueOf(pwdPasswordConfirm.getPassword());
        
        if(idadmin.trim().equals("id admin") || namaadmin.trim().equals("nama admin") || 
           pass.trim().equals("password") || passconf.trim().equals("password"))
        {
            JOptionPane.showMessageDialog(null, "Terdapat Data yang Kosong", "Register Error",2);
            return false;
        }
        else if(!pass.equals(passconf))
        {
            JOptionPane.showMessageDialog(null, "Konfirmasi Password Salah", "Register Error",2);
            return false;
        }
        else{
            return true;
        }
    }
    
    public boolean checkKodePetugas(String idadmin){
        PreparedStatement st;
        ResultSet rs;
        boolean idadmin_exist = false;
        
        String query = "SELECT * FROM `admin` WHERE `id_admin` = ?";
        
        try {
            st = connection.getConnection().prepareStatement(query);
            
            st.setString(1, idadmin);
            rs = st.executeQuery();
            
            if(rs.next())
            {
                idadmin_exist = true;
                JOptionPane.showMessageDialog(null, "ID Admin Sudah Digunakan", "Register Error", 2);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(RegisterFormAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        return idadmin_exist;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterFormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterFormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterFormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterFormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterFormAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblChange;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblMinimize;
    private java.awt.Panel panel1;
    private javax.swing.JPasswordField pwdPassword;
    private javax.swing.JPasswordField pwdPasswordConfirm;
    private javax.swing.JTextField txtIDAdmin;
    private javax.swing.JTextField txtNamaAdmin;
    // End of variables declaration//GEN-END:variables
}
